name: Validate and Update Subdomains

on:
  push:
    paths:
      - "subdomains/**"

jobs:
  validate-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Get changed subdomain files
        id: diff
        run: |
          # Check if previous commit exists; fallback to all files in subdomains/ if not
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "First commit or no previous commit found. Processing all subdomain files."
            find subdomains -type f > changed-files.txt
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^subdomains/' > changed-files.txt || echo "No changes"
          fi

      - name: Display changed files
        run: cat changed-files.txt

      - name: Validate and Update Subdomains
        if: success() && steps.diff.outputs.changed-files != ''
        run: |
          for file in $(cat changed-files.txt); do
            echo "Processing $file"
            node scripts/validate.js $file && node scripts/update.js $file;
          done
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
